spring.application.name=travelplanai
server.port=8080

# Configuración de Google Gemini API
gemini.api.key=PON_AQUI_TU_API_KEY
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent

logging.level.com.travelplan=DEBUG